---
title: "SPACE Analyses"
author: "Erik Nook, Eli Lebowitz, Dylan Gee"
date: "1/17/2022"
output: 
  html_document:
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

<style type="text/css">

body{ /* Normal  */
font-size: 11px;
}
code.r{ /* Code block */
font-size: 11px;
}
pre { /* Code block - determines code spacing between lines */
font-size: 11px;
}
</style>

```{r prep, error=F, message=FALSE, warning=F, include=F}
##-----------Attach Packages-----
if (!require("Rmisc")) {install.packages("Rmisc"); require("Rmisc")}
if (!require("dplyr")) {install.packages("dplyr"); require("dplyr")} 
if (!require("reshape2")) {install.packages("reshape2"); require("reshape2")} 
if (!require("lme4")) {install.packages("lme4"); require("lme4")} 
if (!require("lmerTest")) {install.packages("lmerTest"); require("lmerTest")} 
if (!require("effects")) {install.packages("effects"); require("effects")} 
if (!require("parameters")) {install.packages("parameters"); require("parameters")}
if (!require("psych")) {install.packages("psych"); require("psych")}
if (!require("reghelper")) {install.packages("reghelper"); require("reghelper")}
if (!require("effectsize")) {install.packages("effectsize"); require("effectsize")}

#
##-----------Load and process data-------
setwd("/Users/en7113/Dropbox (Personal)/Yale_Postdoc/Research/SPACE/OSF")

d <- read.csv("SPACE_Data.csv")
d$SID <- as.factor(d$SID)
SIDs <- unique(d$SID)

# compute linguistic distance measure
d$SixltrZ <- scale(d$Sixltr)
d$articleZ <- scale(d$article)
d$iZ <- -1*scale(d$i)
d$discrepZ <- -1*scale(d$discrep)
d$presentZ <- -1*scale(d$present)
d$lingdist <- rowMeans(d[,c("SixltrZ", "articleZ", "iZ", "discrepZ", "presentZ")])

# Make child and parent columns for each variable depending on speaker
lingCols <- c("WC","WC_log","lingdist","posemo","negemo","posemo_bin","negemo_bin")
d[,paste0(lingCols,"_C")] <- d[,lingCols]
d[,paste0(lingCols,"_C_l")] <- NA
d[d$Speaker=="adult",paste0(lingCols,"_C")] <- NA
d[,paste0(lingCols,"_A")] <- d[,lingCols]
d[,paste0(lingCols,"_A_l")] <- NA
d[d$Speaker=="child",paste0(lingCols,"_A")] <- NA

# split into child and adult datasets
d_C <- d[d$Speaker=="child",]
d_A <- d[d$Speaker=="adult",]

# Make child leads / adult leads datasets
d_childLeads <- NULL
for (s in SIDs) {
  dc <- d_C[d_C$SID==s,]
  da <- d_A[d_A$SID==s,]
  
  if (nrow(dc) > 0 & nrow(da) > 0) {
    if (dc$Turn[1] == 2) {da <- da[-1,]}
    dcl <- dc[1:min(nrow(da),nrow(dc)),]
    dcl[,paste0(lingCols,"_A")] <- da[1:min(nrow(da),nrow(dc)),paste0(lingCols,"_A")]
    dcl[,paste0(lingCols,"_A_l")] <- lag(da[1:min(nrow(da),nrow(dc)),paste0(lingCols,"_A")])
    dcl$Exchange <- 1:nrow(dcl)
    dcl$adultTurn <- da[1:min(nrow(da),nrow(dc)),"adultTurn"]
    
    if (is.null(d_childLeads)) {d_childLeads <- dcl} else {d_childLeads <- rbind(d_childLeads,dcl)}
  }
}

d_adultLeads <- NULL
for (s in SIDs) {
  dc <- d_C[d_C$SID==s,]
  da <- d_A[d_A$SID==s,]
  
  if (nrow(dc) > 0 & nrow(da) > 0) {
    if (da$Turn[1] == 2) {dc <- dc[-1,]}
    dal <- da[1:min(nrow(da),nrow(dc)),]
    dal[,paste0(lingCols,"_C")] <- dc[1:min(nrow(da),nrow(dc)),paste0(lingCols,"_C")]
    dal[,paste0(lingCols,"_C_l")] <- lag(dc[1:min(nrow(da),nrow(dc)),paste0(lingCols,"_C")])
    dal$Exchange <- 1:nrow(dal)
    dal$childTurn <- dc[1:min(nrow(da),nrow(dc)),"childTurn"]
    
    if (is.null(d_adultLeads)) {d_adultLeads <- dal} else {d_adultLeads <- rbind(d_adultLeads,dal)}
  }
}

#check alignment
#d_childLeads[,c("SID","Session","Turn","Exchange","childTurn","adultTurn","WC_A","WC_A_l")]
#d_adultLeads[,c("SID","Session","Turn","Exchange","adultTurn","childTurn","WC_C","WC_C_l")]
# 

#Set SIDs as factors
d_childLeads$SID <- as.factor(d_childLeads$SID)
d_adultLeads$SID <- as.factor(d_adultLeads$SID)

#
```

***  


## Table 1

``` {r sampleDescription, warning=F}
#Subjects 
d_Ps <- d[d$Turn==1,]
N <- nrow(d_Ps)
N

#Child age
min(d_Ps$ChildAge,na.rm=T)
max(d_Ps$ChildAge,na.rm=T)
mean(d_Ps$ChildAge,na.rm=T)
sd(d_Ps$ChildAge,na.rm=T)

#Child sex
table(d_Ps$ChildSex)
round((table(d_Ps$ChildSex)/N)*100,2)

#Parent sex
table(d_Ps$ParentSex)
round(table(d_Ps$ParentSex)/(N-sum(is.na(d_Ps$ParentSex)))*100,2)

#Child race
sum(is.na(d_Ps$ChildRace))
table(d_Ps$ChildRace)
round(table(d_Ps$ChildRace)/(N-sum(is.na(d_Ps$ChildRace)))*100,2)

#Child ethnicity
sum(is.na(d_Ps$ChildEthnicity))
table(d_Ps$ChildEthnicity)
round(table(d_Ps$ChildEthnicity)/(N-sum(is.na(d_Ps$ChildEthnicity)))*100,2)

#Parent race
sum(is.na(d_Ps$ParentRace))
table(d_Ps$ParentRace)
round(table(d_Ps$ParentRace)/(N-sum(is.na(d_Ps$ParentRace)))*100,2)

#Parent ethnicity
sum(is.na(d_Ps$ParentEthnicity))
table(d_Ps$ParentEthnicity)
round(table(d_Ps$ParentEthnicity)/(N-sum(is.na(d_Ps$ParentEthnicity)))*100,2)

#Family Income
sum(is.na(d_Ps$FamilyIncome))
table(d_Ps$FamilyIncome)
round(table(d_Ps$FamilyIncome)/(N-sum(is.na(d_Ps$FamilyIncome)))*100,2)

#Word count
WCtotals <- tapply(d$WC, d[,c("SID","Speaker")], sum, na.rm=T) 
mean(WCtotals); sd(WCtotals) #average and sd words/person across all people
colMeans(WCtotals)
sd(WCtotals[,1])
sd(WCtotals[,2])

#Turns
nrow(d) #Turns
sum(d$Speaker=="child"); sum(d$Speaker=="child")/length(d$WC)*100 #Child turns
sum(d$Speaker=="adult"); sum(d$Speaker=="adult")/length(d$WC)*100 #Adult turns

#Audible words/turn (word count)
mean(d$WC,na.rm=T)
sd(d$WC,na.rm=T)
mean(d$WC[d$Speaker=="child"],na.rm=T)
sd(d$WC[d$Speaker=="child"],na.rm=T)
mean(d$WC[d$Speaker=="adult"],na.rm=T)
sd(d$WC[d$Speaker=="adult"],na.rm=T)

#Inaudible turns
sum(is.na(d$WC))
sum(is.na(d$WC))/length(d$WC)*100
sum(is.na(d$WC[d$Speaker=="child"]))
sum(is.na(d$WC[d$Speaker=="child"]))/length(d$WC[d$Speaker=="child"])*100
sum(is.na(d$WC[d$Speaker=="adult"]))
sum(is.na(d$WC[d$Speaker=="adult"]))/length(d$WC[d$Speaker=="child"])*100

#Inaudible words/turn
mean(d$inadubles,na.rm=T)
mean(d$inadubles/(d$WC+d$inadubles),na.rm=T)*100
mean(d$inadubles[d$Speaker=="child"],na.rm=T)
mean(d$inadubles[d$Speaker=="child"]/(d$WC[d$Speaker=="child"]+d$inadubles[d$Speaker=="child"]),na.rm=T)*100
mean(d$inadubles[d$Speaker=="adult"],na.rm=T)
mean(d$inadubles[d$Speaker=="adult"]/(d$WC[d$Speaker=="adult"]+d$inadubles[d$Speaker=="adult"]),na.rm=T)*100


```



## Negative Affect Word Analyses

``` {r negemo, warning=F}

#Child leads
M1_cl <- glmer(negemo_bin_A ~ negemo_bin_C + negemo_bin_A_l + (1 | SID), data = d_childLeads, family = binomial)
M1b_cl <- glmer(negemo_bin_A ~ negemo_bin_C + negemo_bin_A_l + (negemo_bin_C | SID), data = d_childLeads, family = binomial)
M1c_cl <- glmer(negemo_bin_A ~ negemo_bin_C + negemo_bin_A_l + (negemo_bin_A_l | SID), data = d_childLeads, family = binomial)
M1d_cl <- glmer(negemo_bin_A ~ negemo_bin_C + negemo_bin_A_l + (negemo_bin_C + negemo_bin_A_l | SID), data = d_childLeads, family = binomial)
anova(M1_cl, M1b_cl)
anova(M1_cl, M1c_cl)
anova(M1_cl, M1d_cl)
exp(cbind(est=fixef(M1_cl),confint(M1_cl, parm="beta_", method = "Wald")))
summary(M1_cl)
confint(M1_cl, method="Wald")
p_negemo_cl <- summary(M1_cl)$coefficients[2,4]

#Parent leads
M1_pl <- glmer(negemo_bin_C ~ negemo_bin_A + negemo_bin_C_l + (1 | SID), data = d_adultLeads, family = binomial)
M1b_pl <- glmer(negemo_bin_C ~ negemo_bin_A + negemo_bin_C_l + (negemo_bin_A | SID), data = d_adultLeads, family = binomial)
M1c_pl <- glmer(negemo_bin_C ~ negemo_bin_A + negemo_bin_C_l + (negemo_bin_C_l | SID), data = d_adultLeads, family = binomial)
M1d_pl <- glmer(negemo_bin_C ~ negemo_bin_A + negemo_bin_C_l + (negemo_bin_A + negemo_bin_C_l | SID), data = d_adultLeads, family = binomial)
anova(M1_pl, M1b_pl)
anova(M1_pl, M1c_pl)
anova(M1_pl, M1d_pl)
exp(cbind(est=fixef(M1_pl),confint(M1_pl, parm="beta_", method = "Wald")))
summary(M1_pl)
confint(M1_pl, method="Wald")
p_negemo_pl <- summary(M1_pl)$coefficients[2,4]

```


## Positive Affect Word Analyses

``` {r posemo, warning=F}
#Child leads
M1_cl <- glmer(posemo_bin_A ~ posemo_bin_C + posemo_bin_A_l + (1 | SID), data = d_childLeads, family = binomial)
M1b_cl <- glmer(posemo_bin_A ~ posemo_bin_C + posemo_bin_A_l + (posemo_bin_C | SID), data = d_childLeads, family = binomial)
M1c_cl <- glmer(posemo_bin_A ~ posemo_bin_C + posemo_bin_A_l + (posemo_bin_A_l | SID), data = d_childLeads, family = binomial)
M1d_cl <- glmer(posemo_bin_A ~ posemo_bin_C + posemo_bin_A_l + (posemo_bin_C+posemo_bin_A_l | SID), data = d_childLeads, family = binomial)
anova(M1_cl, M1b_cl)
anova(M1_cl, M1c_cl)
anova(M1_cl, M1d_cl)
exp(cbind(est=fixef(M1_cl),confint(M1_cl, parm="beta_", method = "Wald")))
summary(M1_cl)
confint(M1_cl, method="Wald")
p_posemo_cl <- summary(M1_cl)$coefficients[2,4]

#Parent leads
M1_pl <- glmer(posemo_bin_C ~ posemo_bin_A + posemo_bin_C_l + (1 | SID), data = d_adultLeads, family = binomial)
M1b_pl <- glmer(posemo_bin_C ~ posemo_bin_A + posemo_bin_C_l + (posemo_bin_A | SID), data = d_adultLeads, family = binomial)
M1c_pl <- glmer(posemo_bin_C ~ posemo_bin_A + posemo_bin_C_l + (posemo_bin_C_l | SID), data = d_adultLeads, family = binomial)
M1d_pl <- glmer(posemo_bin_C ~ posemo_bin_A + posemo_bin_C_l + (posemo_bin_A+posemo_bin_C_l | SID), data = d_adultLeads, family = binomial)
anova(M1_pl, M1b_pl)
anova(M1_pl, M1c_pl)
anova(M1_pl, M1d_pl)
exp(cbind(est=fixef(M1_pl),confint(M1_pl, parm="beta_", method = "Wald")))
summary(M1_pl)
confint(M1_pl, method="Wald")
p_posemo_pl <- summary(M1_pl)$coefficients[2,4]

```



## Linguistic Distance Analyses

``` {r lingdist, warning=F}
#Child leads
M1_cl <- lmer(lingdist_A ~ lingdist_C + lingdist_A_l + (1 | SID), data = d_childLeads)
M1b_cl <- lmer(lingdist_A ~ lingdist_C + lingdist_A_l + (lingdist_C | SID), data = d_childLeads)
M1c_cl <- lmer(lingdist_A ~ lingdist_C + lingdist_A_l + (lingdist_A_l | SID), data = d_childLeads)
M1d_cl <- lmer(lingdist_A ~ lingdist_C + lingdist_A_l + (lingdist_C + lingdist_A_l | SID), data = d_childLeads)
anova(M1_cl, M1b_cl)
anova(M1_cl, M1c_cl)
anova(M1_cl, M1d_cl)
myOut <- standardize_parameters(M1_cl, method="basic")
myOut
myOut$CI_low[2] #unrounded CI_low for lingdist_C
summary(M1_cl)
confint(M1_cl, method="Wald")
p_lingdist_cl <- summary(M1_cl)$coefficients[2,5]

#Parent leads
M1_pl <- lmer(lingdist_C ~ lingdist_A + lingdist_C_l + (1 | SID), data = d_adultLeads)
M1b_pl <- lmer(lingdist_C ~ lingdist_A + lingdist_C_l + (lingdist_A | SID), data = d_adultLeads)
M1c_pl <- lmer(lingdist_C ~ lingdist_A + lingdist_C_l + (lingdist_C_l | SID), data = d_adultLeads)
M1d_pl <- lmer(lingdist_C ~ lingdist_A + lingdist_C_l + (lingdist_A + lingdist_C_l| SID), data = d_adultLeads)
anova(M1_pl, M1b_pl)
anova(M1_pl, M1c_pl)
anova(M1c_pl, M1d_pl)
standardize_parameters(M1c_pl, method="basic")
summary(M1c_pl)
confint(M1c_pl, method = "Wald")
p_lingdist_pl <- summary(M1c_pl)$coefficients[2,5]

```


## Word Count

``` {r WC, warning=F}
#Child leads
M1_cl <- lmer(WC_log_A ~ WC_log_C + WC_log_A_l + (1 | SID), data = d_childLeads)
M1b_cl <- lmer(WC_log_A ~ WC_log_C + WC_log_A_l + (WC_log_C | SID), data = d_childLeads)
M1c_cl <- lmer(WC_log_A ~ WC_log_C + WC_log_A_l + (WC_log_A_l | SID), data = d_childLeads)
M1d_cl <- lmer(WC_log_A ~ WC_log_C + WC_log_A_l + (WC_log_C+WC_log_A_l | SID), data = d_childLeads)
anova(M1_cl, M1b_cl)
anova(M1_cl, M1c_cl)
anova(M1_cl, M1d_cl)
standardize_parameters(M1_cl, method="basic")
summary(M1_cl)
confint(M1_cl, method = "Wald")
p_WC_cl <- summary(M1_cl)$coefficients[2,5]

#Parent leads
M1_pl <- lmer(WC_log_C ~ WC_log_A + WC_log_C_l + (1 | SID), data = d_adultLeads)
M1b_pl <- lmer(WC_log_C ~ WC_log_A + WC_log_C_l + (WC_log_A | SID), data = d_adultLeads)
M1c_pl <- lmer(WC_log_C ~ WC_log_A + WC_log_C_l + (WC_log_C_l | SID), data = d_adultLeads)
M1d_pl <- lmer(WC_log_C ~ WC_log_A + WC_log_C_l + (WC_log_A+WC_log_C_l | SID), data = d_adultLeads)
anova(M1_pl, M1b_pl)
anova(M1_pl, M1c_pl)
anova(M1_pl, M1d_pl)
standardize_parameters(M1_pl, method="basic")
summary(M1_pl)
confint(M1_pl, method = "Wald")
p_WC_pl <- summary(M1_pl)$coefficients[2,5]

```
